name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "src/Portfolio/**"
  pull_request:
    branches: [main]
    paths:
      - "src/Portfolio/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore src/Portfolio/Portfolio.csproj

      - name: Build
        run: dotnet build src/Portfolio/Portfolio.csproj --no-restore --configuration Release

      - name: Publish
        run: dotnet publish src/Portfolio/Portfolio.csproj --no-build --configuration Release --output dist

      - name: Copy index.html to 404.html (for GitHub Pages SPA support)
        run: cp dist/wwwroot/index.html dist/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch dist/wwwroot/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/wwwroot

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
